### ISSUE TITLE
Both Transactions and User Commands tabs are highlighted on the accounts spotlight page when viewing User Commands

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-block-explorer#957] opened 2024-07-25 20:36 UTC
<img width="1800" alt="Screenshot 2024-07-25 at 3 53 45 PM" src="https://github.com/user-attachments/assets/49847f58-4c6f-48af-835a-f3c7fecb22b5">

**Comment by n1tranquilla** [comment] 2024-07-29 11:36
Duplicate of #958

**Closed by n1tranquilla** 2024-07-29 11:36 UTC
Labels: Bug
