### ISSUE TITLE
Internal Commands: Filtering by height has no effect

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-block-explorer#681] opened 2024-05-24 12:32 UTC
![2024-05-24 09 30 02](https://github.com/Granola-Team/mina-block-explorer/assets/19426804/5b8d988e-604a-404a-9d9c-3e5c278d0cbd)

**Comment by trevorbernard** [comment] 2024-05-26 19:31
Resolved by: https://github.com/Granola-Team/mina-indexer/pull/959

**Comment by robinbb** [comment] 2024-05-27 03:37
This is in the Done column, but not closed. I will close. @n1tranquilla re-open if the issue is not resolved, please.

**Closed by robinbb** 2024-05-27 03:37 UTC
Labels: indexer-integration
